### ISSUE TITLE
Make todo item

### ISSUE THREAD

**Issue by ped59430** [ped59430/todo#3]
- [x] Remove bin
- [x] Remove check box
- [x] Use q component with slide
- [x] Put a white shadow
- [x] Format the inside element of the slide with padding
- [x] Make round corners for the inside and outside of the slide

**Comment by ped59430** [comment]
Move Combine the inside component with an input component to another issue
